AWSTemplateFormatVersion: '2010-09-09'
Description: 'IBKR Tax Calculator - CloudFront + SSL + DNS (us-east-1 only)'

Parameters:
  DomainName:
    Type: String
    Default: cgttaxtool.uk
    Description: The domain name for the website
  
  S3BucketName:
    Type: String
    Default: cgttaxtool-static-286154443186
    Description: The S3 bucket name in eu-west-1
  
  ApiGatewayId:
    Type: String
    Default: wwyo166mwh
    Description: The API Gateway ID in eu-west-1

Resources:
  # SSL Certificate (must be in us-east-1 for CloudFront)
  SSLCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      SubjectAlternativeNames:
        - !Sub 'www.${DomainName}'
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          HostedZoneId: Z09016191Q8ZEJ35X4XQA
        - DomainName: !Sub 'www.${DomainName}'
          HostedZoneId: Z09016191Q8ZEJ35X4XQA

  # CloudFront Distribution
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref DomainName
          - !Sub 'www.${DomainName}'
        Comment: !Sub 'IBKR Tax Calculator - ${DomainName}'
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
          ResponseHeadersPolicyId: 5cc3b908-e619-4b99-88e5-2cf7f45965bd
        CacheBehaviors:
          - PathPattern: '/api/*'
            TargetOriginId: APIGateway
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods: [GET, HEAD, OPTIONS, PUT, POST, PATCH, DELETE]
            CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
            OriginRequestPolicyId: b689b0a8-53d0-40ab-baf2-68738e2966ac
            ResponseHeadersPolicyId: 5cc3b908-e619-4b99-88e5-2cf7f45965bd
        Origins:
          - Id: S3Origin
            DomainName: !Sub '${S3BucketName}.s3.eu-west-1.amazonaws.com'
            S3OriginConfig:
              OriginAccessIdentity: ''
          - Id: APIGateway
            DomainName: !Sub '${ApiGatewayId}.execute-api.eu-west-1.amazonaws.com'
            CustomOriginConfig:
              HTTPPort: 443
              OriginProtocolPolicy: https-only
            OriginPath: '/prod'
        Enabled: true
        DefaultRootObject: index.html
        ViewerCertificate:
          AcmCertificateArn: !Ref SSLCertificate
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021

  # DNS Records
  DNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: Z09016191Q8ZEJ35X4XQA
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2

  WWWDNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: Z09016191Q8ZEJ35X4XQA
      Name: !Sub 'www.${DomainName}'
      Type: A
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2

Outputs:
  CloudFrontUrl:
    Description: CloudFront distribution URL
    Value: !GetAtt CloudFrontDistribution.DomainName

  WebsiteUrl:
    Description: Complete website URL
    Value: !Sub 'https://${DomainName}'

  SSLCertificateArn:
    Description: SSL Certificate ARN
    Value: !Ref SSLCertificate

  CloudFrontDistributionId:
    Description: CloudFront Distribution ID
    Value: !Ref CloudFrontDistribution
